version: "3.7"

services:
  tank:
    image: direvius/yandex-tank
    volumes:
      - .:/var/loadtest
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    network_mode: "host"
